"""add created date to url

Revision ID: 75323ad510d4
Revises: 6fa5ffc70255
Create Date: 2023-07-07 16:23:19.926899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75323ad510d4'
down_revision = '6fa5ffc70255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('url', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
